name: Teravince

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository  
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build & Push Backend
    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        pull: true
        tags: ussoppqq/capstone-teravince-backend:latest

    # 4. Build & Push Frontend
    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        pull: true
        tags: ussoppqq/capstone-teravince-frontend:latest
